name: Reusable Workflow user


on: 
   workflow_dispatch:

jobs:    
 test_caller_job:
    runs-on: ubuntu-latest
    steps:
     - name:  Build nexus container
       id:  nexus
       uses: amikshas/ActionTest1@main
 
 
     
    
 
